import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tail Comp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/tail-comp-logo.png" />
      </Head>
      <div>
        <video
          loop="true"
          className="mx-auto"
          autoPlay
          src="/tail_comp_vid.mp4"
        ></video>
      </div>
    </div>
  );
}
